### ISSUE TITLE
macOS readlink does not have -f flag

### ISSUE THREAD

**Issue by Coneko** [nixie-dev/nixie#10]
Not sure if this is supported or even intended to work, but right off the bat I hit:

```
% ./nix --help
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./nix: line 55: : No such file or directory
Could not find or decompress resource archive.
This script can be rebuilt using the nixie tool
tar: Error opening archive: Unrecognized archive format
zsh: abort      ./nix --help
The resource archive is missing or malformed.
This script can be rebuilt using the nixie tool
./nix: line 50: kill: (19685) - No such process
```

because bsd readlink doesn't support `-f` like gnu coreutils readlink does.

**Comment by Thesola10** [comment]
Must have been an oversight, I did test the script on vanilla macOS before.

**Comment by Thesola10** [comment]
`readlink -f` exists on macOS 12, what macOS version did you use?

**Comment by Thesola10** [comment]
What do you think of embedding [realpath-lib](https://github.com/AsymLabs/realpath-lib) into the generated Nixie script? I could have the builder prepend it to the generated script file.
