### ISSUE TITLE
SSL connect error with Nixie

### ISSUE THREAD

**Issue by twesterhout** [nixie-dev/nixie#6]
Hello,

I'm trying to replace my usage of nix-portable with Nixie, but have stumbled upon a problem that the `nix` script can't download the cache:

```
$ ./nix shell nixpkgs#hello
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 259 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 576 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 1102 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 2446 ms
error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35)
```

Is there a known workaround for it? or do you have any ideas how I could debug it further?

Thanks!

**Comment by Thesola10** [comment]
If your system isn't running OpenSSL (maybe it uses LibreSSL?) set `NIX_SSL_CERT_FILE` in the environment to point to your `ca_certificates` bundle. Please share details about what operating system you are running Nixie on.

The issue should not occur on macOS as Nixie sets it to the macOS bundle file, which worked in my testing.

**Comment by twesterhout** [comment]
Thanks! `NIX_SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt` did the trick. I'm running on a supercomputing cluster, it's using Rocky Linux 8.7.

**Comment by Thesola10** [comment]
Cool! I think sourcing `/etc/lsb_release` and checking for Rocky should do the trick?

**Comment by twesterhout** [comment]
That'd be great, yeah.
```sh
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.7 (Green Obsidian)
Release:        8.7
Codename:       GreenObsidian
```

**Comment by Thesola10** [comment]
I have another idea: Can you run `openssl info -configdir`? Does it print the same `/etc/pki/tls` path?

**Comment by twesterhout** [comment]
By the way, There's no `/etc/lsb_release` on the system, hence the `lsb_release -a` command.
I'm not too familiar with OpenSSL, but it seems that checking for the existence of `/etc/pki/...` is simpler that special casing for Rocky, and I don't see any downsides to it either.

Also, `openssl info` returns an error saying that `info` isn't a valid command. It's probably just a very old version: `OpenSSL 1.1.1k  FIPS 25 Mar 2021`
